name: "Deploy para VPS"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4

      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "217.196.60.116"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/sistema"

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "217.196.60.116"
          username: "root"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /sistema
            composer install --no-dev --no-progress -a
            php artisan optimize
            chown -R www-data:www-data .
